version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: v3
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
            exclude:
              - os: windows
                node_version: latest
              - os: windows
                node_version: maintenance
      - release-management/release-package:
          # TODO: add these back when we're ready to GA v3
          # github-release: true
          # post-job-steps:
          #   - run: yarn ci-docs
          tag: 'v3-beta'
          requires:
            - release-management/test-package
          filters:
            branches:
              only: v3
          context:
            - CLI_CTC
            - salesforce-cli
