version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
parameters:
  workflow:
    description: |
      String that controls which workflow would run.

      This parameter is used by automation to determine if a workflow will run
      within a pipeline.
    type: string
    default: 'test-and-release'
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
            exclude:
              - os: windows
                node_version: latest
              - os: windows
                node_version: maintenance
      - release-management/release-package:
          github-release: true
          # TODO: remove once we have docs to publish
          # post-job-steps:
          # - run: yarn ci-docs
          requires:
            - release-management/test-package
          filters:
            branches:
              only: main
          context:
            - CLI_CTC
            - salesforce-cli
      - release-management/test-nut:
          no_output_timeout: 30m
          matrix:
            parameters:
              os:
                - linux
                - windows
              sfdx_version:
                - latest
              node_version:
                - latest
          requires:
            - release-management/test-package
          context:
            - salesforce-cli-na40-auth-url
  test-ts-update:
    when:
      equal: [test-ts-update, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/test-ts-update
  dependabot-automerge:
    when:
      equal: [dependabot-automerge, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/dependabot-automerge:
          filters:
            branches:
              only: main
          context: salesforce-cli
